<?
$PERM["forum"]["8"]="W";
$PERM["forum"]["7"]="W";
$PERM["blogs"]["8"]="W";
$PERM["blogs"]["7"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["7"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>